services:
  
  event.api:
    image: event.api
    build:
      context: ../
      dockerfile: Services/Events.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Database=Host=eventdb;Port=5432;Database=EventDb;Username=postgres;Password=Dachi123;Include Error Detail=true
    ports:
      - "6000:8080"
    depends_on:
      - eventdb
  
  basket.api:
    image: basket.api
    build:
      context: ../
      dockerfile: Services/Basket.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Database=Host=basketdb;Port=5432;Database=BasketDb;Username=postgres;Password=Dachi123;Include Error Detail=true
      - GrpcSettings__DiscountUrl=http://discount.grpc:8080
    ports:
      - "6001:8080"
    depends_on:
      - basketdb
  
  discount.grpc:
    image: discount.grpc
    build:
      context: ../
      dockerfile: Services/Discount.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Database=Host=discountdb;Port=5432;Database=DiscountDb;Username=postgres;Password=Dachi123;Include Error Detail=true
    ports:
      - "6002:8080"
    depends_on:
      - discountdb
  
  eventdb:
    container_name: eventdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: EventDb
      POSTGRES_PASSWORD: Dachi123
    ports:
      - "5432:5432"
    volumes:
      - eventdb_data:/var/lib/postgresql/data

  basketdb:
    container_name: basketdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: BasketDb
      POSTGRES_PASSWORD: Dachi123
    ports:
      - "5433:5432"
    volumes:
      - basketdb_data:/var/lib/postgresql/data
  
  discountdb:
    container_name: discountdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: DiscountDb
      POSTGRES_PASSWORD: Dachi123
    ports:
      - "5434:5432"
    volumes:
      - discountdb_data:/var/lib/postgresql/data

volumes:
  eventdb_data:
  basketdb_data:
  discountdb_data: